name: Build STMCubeIDE

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build CubeIDE project
        uses: xanderhendriks/action-build-stm32cubeide@v12.0
        with:
            project-path: 'ci-pipeline-test'
            project-target: 'ci-pipeline-test'
